eureka:
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #指定实例id
  client:
    service-url:
      defaultZone: http://localhost:7080/eureka/
server:
  port: '8083'
spring:
  application:
    name: service-feign
  zipkin:
    base-url: http://localhost:9411
  #zipkin，Sleuth 默认采样算法的实现是 Reservoir sampling，具体的实现类是 PercentageBasedSampler，默认的采样比例为:
  #0.1，即 10%。我们可以通过 spring.sleuth.sampler.probability 来设置，所设置的值介于 0 到 1 之间，1 则表示全部采集
  sleuth:
    sampler:
      probability: 1.0
    #  boot:
      #    admin:
      #      client:
      #       url:
      #       - http://localhost:8084
        
feign: 
  hystrix: 
      enabled: true #开启Feign Hystrix 支持 高版本需要手动打开
  cloud:
    loadbalancer:
      retry:
        enabled: true #开启重试

ribbon:
  MaxAutoRetries: 1                 #同一实例上的最大重试次数, 默认值为0. 不包括首次调用(需要负载的情况下触发)
  MaxAutoRetriesNextServer: 0       #重试其他实例的最大重试次数, 不包括第一次选的实例. 默认为1(需要负载的情况下触发)
  ReadTimeout: 10000                 #请求处理的超时时间（我们是通过ServerId去找服务的，所以超时策略需要通过ribbon）
  ConnectTimeout: 10000              #请求连接的超时时间（我们是通过ServerId去找服务的，所以超时策略需要通过ribbon）
  OkToRetryOnAllOperations: true   #是否所有操作执行重试, 默认值为false, 只重试`GET`请求
  MaxTotalHttpConnections: 500        #最大连接数
  MaxConnectionsPerHost: 100          #每个host的最大连接数
  #RetryableStatusCodes: 404,502     #何种响应状态码才进行重试
  
#配置断路器超时时间，默认是1000（1秒）
hystrix:
  command: 
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 80000
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
      