eureka:
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #指定实例id
  client:
    service-url:
      defaultZone: http://localhost:7080/eureka/

server:
  port: '8889'
spring:
  application:
    name: hello-spring-cloud-config-client
  cloud:
    config:
      discovery:
        enabled: true
        service-id: hello-spring-cloud-config #配置中心的serviceId，即服务名
      # 配置服务中心的网址
      #uri: http://localhost:8888
      # 配置文件名称的前缀 {application}部分　多个用配置文件用,隔开
      name: config-client
      # 配置仓库的分支
      label: master
      # 配置文件的环境标识 {profile}部分
      profile: dev
    #消息总线配置
    bus:
      enabled: true
      trace:
        enabled: true
      refresh:
        enabled: true  #开启总线消息更新功能

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: AUTO

  zipkin:
    base-url: http://localhost:9411
  #zipkin，Sleuth 默认采样算法的实现是 Reservoir sampling，具体的实现类是 PercentageBasedSampler，默认的采样比例为:
  #0.1，即 10%。我们可以通过 spring.sleuth.sampler.probability 来设置，所设置的值介于 0 到 1 之间，1 则表示全部采集
  sleuth:
    sampler:
      probability: 1.0


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
